export const POPULAR_SONGS = "POPULAR_SONGS";
export const POPULAR_PLAYLISTS = "POPULAR_PLAYLISTS";
export const POPULAR_ALBUMS = "POPULAR_ALBUMS";
export const START_LOADING = "START_LOADING";
export const STOP_LOADING = "STOP_LOADING";

export const PLAY_SONG = "PLAY_SONG";
export const PLAY_PAUSE = "PAUSE_PAUSE";
export const PLAY_JUST = "PLAY_JUST";

export const CURRENT_PLAYLIST = "CURRENT_PLAYLIST";
export const NEXT_CURRENT_PLAYLIST_SONG = " NEXT_CURRENT_PLAYLIST_SONG";
export const PREV_CURRENT_PLAYLIST_SONG = " PREV_CURRENT_PLAYLIST_SONG";
export const CLEAR_PLAYLIST_LOGIC = "CLEAR_PLAYLIST_LOGIC";
export const MINUS_NEXT_CURRENT_PLAYLIST_SONG =
  "MINUS_NEXT_CURRENT_PLAYLIST_SONG";
export const MINUS_PREV_CURRENT_PLAYLIST_SONG =
  "MINUS_PREV_CURRENT_PLAYLIST_SONG";

export const SEARCH_TRACKS = "SEARCH_TRACKS";
export const SEARCH_MORE_TRACKS = "SEARCH_MORE_TRACKS";
export const SEARCH_ALBUMS = "SEARCH_ALBUMS";
export const SEARCH_PLAYLISTS = "SEARCH_PLAYLISTS";

export const RESET_NEXT = "RESET_NEXT";

export const FAVORITE_TRACKS = "FAVORITE_TRACKS";
export const FAVORITE_ALBUMS = "FAVORITE_ALBUMS";
export const FAVORITE_PLAYLISTS = "FAVORITE_PLAYLISTS";
export const PROCESING = "PROCESING";
export const STOP_PROCESING = "STOP_PROCESING";
